# Generated by Django 5.1.4 on 2025-03-21 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0011_remove_tbl_user_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_photo', models.FileField(upload_to='Assets/File/Merchant')),
                ('product_price', models.CharField(max_length=255)),
                ('product_description', models.CharField(max_length=255)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_merchant')),
            ],
        ),
    ]
