# Generated by Django 5.1.4 on 2025-03-21 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_addstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField(auto_now_add=True)),
                ('stock_qty', models.CharField(max_length=200)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Merchant.tbl_product')),
            ],
        ),
    ]
