# Generated by Django 5.1.4 on 2025-02-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_remove_tbl_location_location_name'),
    ]

    operations = [
    ]
