# Generated by Django 5.1.4 on 2025-02-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_auto_20250219_1939'),
        ('Guest', '0003_remove_tbl_user_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_location',
        ),
    ]
