# Generated by Django 5.1.4 on 2025-02-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_location',
            name='district',
        ),
    ]
