# Generated by Django 5.1.4 on 2025-02-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_remove_tbl_location_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_name', models.CharField(max_length=60)),
            ],
        ),
    ]
