# Generated by Django 5.1.4 on 2025-03-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_reply',
        ),
    ]
