# Generated by Django 5.1.4 on 2025-03-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('assign_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=60)),
                ('complaint_content', models.CharField(max_length=200)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_reply', models.CharField(max_length=60)),
                ('complaint_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_plantsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantsman_name', models.CharField(max_length=255)),
                ('plantsman_email', models.EmailField(max_length=254, unique=True)),
                ('plantsman_contact', models.CharField(max_length=15)),
                ('plantsman_address', models.TextField()),
                ('plantsman_photo', models.FileField(upload_to='Assets/File/Coordinator')),
                ('plantsman_proof', models.FileField(upload_to='Assets/File/Coordinator')),
                ('plantsman_password', models.CharField(max_length=255)),
            ],
        ),
    ]
