# Generated by Django 5.1.4 on 2025-03-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
