# Generated by Django 5.1.4 on 2025-03-23 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0003_delete_tbl_complaint'),
        ('Merchant', '0002_tbl_addstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=60)),
                ('complaint_content', models.CharField(max_length=200)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_reply', models.CharField(max_length=60)),
                ('complaint_status', models.IntegerField(default=0)),
                ('plantsman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Coordinator.tbl_plantsman')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Merchant.tbl_product')),
            ],
        ),
    ]
