# Generated by Django 5.1.4 on 2025-03-23 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_delete_tbl_reply'),
        ('Coordinator', '0004_tbl_complaint'),
        ('Guest', '0011_remove_tbl_user_place'),
        ('Merchant', '0002_tbl_addstock'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_assign',
            name='land',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_land'),
        ),
        migrations.AlterField(
            model_name='tbl_assign',
            name='plantsman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coordinator.tbl_plantsman'),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='plantsman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coordinator.tbl_plantsman'),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Merchant.tbl_product'),
        ),
        migrations.AlterField(
            model_name='tbl_plantsman',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_coordinator'),
        ),
        migrations.AlterField(
            model_name='tbl_plantsman',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_location'),
        ),
    ]
