# Generated by Django 5.1.4 on 2025-03-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0005_alter_tbl_assign_land_alter_tbl_assign_plantsman_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
