# Generated by Django 5.1.4 on 2025-03-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0007_tbl_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='product',
        ),
    ]
