# Generated by Django 5.1.4 on 2025-03-23 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0008_remove_tbl_complaint_product'),
        ('Merchant', '0002_tbl_addstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Merchant.tbl_product'),
        ),
    ]
