# Generated by Django 5.1.4 on 2025-03-23 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0009_tbl_complaint_product'),
        ('Guest', '0011_remove_tbl_user_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
    ]
