# Generated by Django 5.1.4 on 2025-04-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0010_tbl_complaint_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_reply',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
