# Generated by Django 5.1.4 on 2025-03-23 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Coordinator', '0001_initial'),
        ('Guest', '0011_remove_tbl_user_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('plantsman_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantsman_from', to='Coordinator.tbl_plantsman')),
                ('plantsman_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantsman_to', to='Coordinator.tbl_plantsman')),
                ('user_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_user')),
                ('user_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_prequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('discription', models.CharField(max_length=200)),
                ('request_status', models.IntegerField(default=0)),
                ('request_amount', models.IntegerField(default=0)),
                ('User_amount', models.CharField(max_length=200, null=True)),
                ('Merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_merchant')),
                ('assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Coordinator.tbl_assign')),
            ],
        ),
    ]
