# Generated by Django 5.1.4 on 2025-02-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='location',
        ),
    ]
