# Generated by Django 5.1.4 on 2025-02-19 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_delete_tbl_location'),
        ('Guest', '0003_remove_tbl_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coor_name', models.CharField(max_length=255)),
                ('coor_email', models.EmailField(max_length=254, unique=True)),
                ('coor_contact', models.CharField(max_length=15)),
                ('coor_address', models.TextField()),
                ('coor_password', models.CharField(max_length=255)),
                ('coor_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_district')),
                ('coor_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
