# Generated by Django 5.1.4 on 2025-02-20 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_location'),
        ('Guest', '0004_tbl_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_coordinator',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_location'),
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_location'),
        ),
    ]
