# Generated by Django 5.1.4 on 2025-02-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_coordinator_location_tbl_user_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_coordinator',
            old_name='coor_address',
            new_name='coordinator_address',
        ),
        migrations.RenameField(
            model_name='tbl_coordinator',
            old_name='coor_contact',
            new_name='coordinator_contact',
        ),
        migrations.RenameField(
            model_name='tbl_coordinator',
            old_name='coor_email',
            new_name='coordinator_email',
        ),
        migrations.RenameField(
            model_name='tbl_coordinator',
            old_name='coor_name',
            new_name='coordinator_name',
        ),
        migrations.RenameField(
            model_name='tbl_coordinator',
            old_name='coor_password',
            new_name='coordinator_password',
        ),
        migrations.RemoveField(
            model_name='tbl_coordinator',
            name='coor_district',
        ),
        migrations.RemoveField(
            model_name='tbl_coordinator',
            name='coor_place',
        ),
        migrations.AddField(
            model_name='tbl_coordinator',
            name='coordinator_photo',
            field=models.FileField(default=2, upload_to='Assets/File/Coordinator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_coordinator',
            name='coordinator_proof',
            field=models.FileField(default=2, upload_to='Assets/File/Coordinator'),
            preserve_default=False,
        ),
    ]
