# Generated by Django 5.1.4 on 2025-02-21 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_location'),
        ('Guest', '0006_rename_coor_address_tbl_coordinator_coordinator_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_email', models.EmailField(max_length=254, unique=True)),
                ('merchant_contact', models.CharField(max_length=15)),
                ('merchant_address', models.TextField()),
                ('merchant_photo', models.FileField(upload_to='Assets/File/Coordinator')),
                ('merchant_proof', models.FileField(upload_to='Assets/File/Coordinator')),
                ('merchant_password', models.CharField(max_length=255)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_location')),
            ],
        ),
    ]
