# Generated by Django 5.1.4 on 2025-02-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_merchant',
            name='merchant_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
