# Generated by Django 5.1.4 on 2025-02-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_merchant_merchant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_coordinator',
            name='coordinator_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_merchant',
            name='merchant_status',
            field=models.IntegerField(default=0),
        ),
    ]
