# Generated by Django 5.1.4 on 2025-02-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_coordinator_coordinator_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_merchant',
            name='merchant_photo',
            field=models.FileField(upload_to='Assets/File/Merchant'),
        ),
        migrations.AlterField(
            model_name='tbl_merchant',
            name='merchant_proof',
            field=models.FileField(upload_to='Assets/File/Merchant'),
        ),
    ]
