# Generated by Django 5.1.4 on 2025-02-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_alter_tbl_merchant_merchant_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='place',
        ),
    ]
