# Generated by Django 5.1.4 on 2025-04-16 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_delete_tbl_reply'),
        ('Guest', '0011_remove_tbl_user_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='location',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_location'),
            preserve_default=False,
        ),
    ]
