# Generated by Django 5.1.4 on 2025-03-23 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0011_remove_tbl_user_place'),
        ('Merchant', '0002_tbl_addstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_amount', models.CharField(max_length=200)),
                ('booking_status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_qty', models.IntegerField(default=1)),
                ('cart_status', models.IntegerField(default=0)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Merchant.tbl_product')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_file', models.FileField(upload_to='Assets/File/land')),
                ('land_details', models.CharField(max_length=200)),
                ('land_proof', models.FileField(upload_to='Assets/File/land')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=0)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_coordinator')),
                ('land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_land')),
            ],
        ),
    ]
